# Build Definition
# Build the complete solution and get ready for deployment

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './ozan-kanik-app-express'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './ozan-kanik'
- task: CmdLine@2
  inputs:
    script: 'npm install -g @angular/cli'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: 'Release' 